Fix conflict between protobuf and OSX include ConditionalMacros.h
Message was:

/Users/garrett/Documents/kodi/tools/depends/target/binary-addons/macosx10.10_x86_64-target/build/depends/include/google/protobuf/descriptor.h:358:5: error:
      expected identifier
    TYPE_BOOL           = 8,   // bool, varint on the wire.
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/ConditionalMacros.h:147:39: note:
      expanded from macro 'TYPE_BOOL'
     #define TYPE_BOOL                1
                                      ^
1 error generated.